export const themes = {
    light: {
        colors: {
            background: "#ffffff",
            foreground: "#111827",
            card: "#ffffff",
            cardForeground: "#111827",
            popover: "#ffffff",
            popoverForeground: "#111827",
            primary: "#111827",
            primaryForeground: "#f9fafb",
            secondary: "#f3f4f6",
            secondaryForeground: "#111827",
            muted: "#f3f4f6",
            mutedForeground: "#6b7280",
            accent: "#f3f4f6",
            accentForeground: "#111827",
            destructive: "#dc2626",
            destructiveForeground: "#ffffff",
            border: "#e5e7eb",
            input: "#e5e7eb",
            ring: "#111827",
            chart1: "#f97316",
            chart2: "#0ea5e9",
            chart3: "#22c55e",
            chart4: "#a855f7",
            chart5: "#f43f5e",
            sidebar: "#ffffff",
            sidebarForeground: "#111827",
            sidebarPrimary: "#111827",
            sidebarPrimaryForeground: "#f9fafb",
            sidebarAccent: "#f3f4f6",
            sidebarAccentForeground: "#111827",
            sidebarBorder: "#e5e7eb",
            sidebarRing: "#111827",
        },
    },
    dark: {
        colors: {
            background: "#0b0b0c",
            foreground: "#f4f4f5",
            card: "#111113",
            cardForeground: "#f4f4f5",
            popover: "#111113",
            popoverForeground: "#f4f4f5",
            primary: "#f4f4f5",
            primaryForeground: "#111827",
            secondary: "#27272a",
            secondaryForeground: "#f4f4f5",
            muted: "#27272a",
            mutedForeground: "#a1a1aa",
            accent: "#27272a",
            accentForeground: "#f4f4f5",
            destructive: "#ef4444",
            destructiveForeground: "#ffffff",
            border: "#27272a",
            input: "#27272a",
            ring: "#d4d4d8",
            chart1: "#8b5cf6",
            chart2: "#22c55e",
            chart3: "#f59e0b",
            chart4: "#0ea5e9",
            chart5: "#f43f5e",
            sidebar: "#111113",
            sidebarForeground: "#f4f4f5",
            sidebarPrimary: "#8b5cf6",
            sidebarPrimaryForeground: "#f4f4f5",
            sidebarAccent: "#27272a",
            sidebarAccentForeground: "#f4f4f5",
            sidebarBorder: "#27272a",
            sidebarRing: "#d4d4d8",
        },
    },
} as const;

export type ThemeName = keyof typeof themes;
export type Theme = (typeof themes)[ThemeName];

export const theme = themes.dark;
